export const USER = {
  SIGN_IN_REQUEST: 'SIGN_IN_REQUEST',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',

  SIGN_OUT_REQUEST: 'SIGN_OUT_REQUEST',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
  SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',

  LOAD_USER_REQUEST: 'LOAD_USER_REQUEST',
  LOAD_USER_SUCCESS: 'LOAD_USER_SUCCESS',
  LOAD_USER_FAILURE: 'LOAD_USER_FAILURE',
};

export const BOOK = {
  LOAD_BOOK_LIST_REQUEST: 'LOAD_BOOK_LIST_REQUEST',
  LOAD_BOOK_LIST_SUCCESS: 'LOAD_BOOK_LIST_SUCCESS',
  LOAD_BOOK_LIST_FAILURE: 'LOAD_BOOK_LIST_FAILURE',

  LOAD_BOOK_LIST_BY_CATEGORY_REQUEST: 'LOAD_BOOK_LIST_BY_CATEGORY_REQUEST',
  LOAD_BOOK_LIST_BY_CATEGORY_SUCCESS: 'LOAD_BOOK_LIST_BY_CATEGORY_SUCCESS',
  LOAD_BOOK_LIST_BY_CATEGORY_FAILURE: 'LOAD_BOOK_LIST_BY_CATEGORY_FAILURE',

  LOAD_BOOK_REQUEST: 'LOAD_BOOK_REQUEST',
  LOAD_BOOK_SUCCESS: 'LOAD_BOOK_SUCCESS',
  LOAD_BOOK_FAILURE: 'LOAD_BOOK_FAILURE',
};

export const CATEGORY = {
  LOAD_CATEGORY_LIST_REQUEST: 'LOAD_CATEGORY_LIST_REQUEST',
  LOAD_CATEGORY_LIST_SUCCESS: 'LOAD_CATEGORY_LIST_SUCCESS',
  LOAD_CATEGORY_LIST_FAILURE: 'LOAD_CATEGORY_LIST_FAILURE',
};
