export const USER = {
  EMAIL_DUPLICATION_CHECK_REQUEST: 'EMAIL_DUPLICATION_CHECK_REQUEST',
  EMAIL_DUPLICATION_CHECK_SUCCESS: 'EMAIL_DUPLICATION_CHECK_SUCCESS',
  EMAIL_DUPLICATION_CHECK_FAILURE: 'EMAIL_DUPLICATION_CHECK_FAILURE',

  SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',

  SIGN_IN_REQUEST: 'SIGN_IN_REQUEST',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',

  SIGN_OUT_REQUEST: 'SIGN_OUT_REQUEST',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
  SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',

  LOAD_USER_REQUEST: 'LOAD_USER_REQUEST',
  LOAD_USER_SUCCESS: 'LOAD_USER_SUCCESS',
  LOAD_USER_FAILURE: 'LOAD_USER_FAILURE',

  PASSWORD_VERIFY_REQUEST: 'PASSWORD_VERIFY_REQUEST',
  PASSWORD_VERIFY_SUCCESS: 'PASSWORD_VERIFY_SUCCESS',
  PASSWORD_VERIFY_FAILURE: 'PASSWORD_VERIFY_FAILURE',

  UPDATE_AVATAR_REQUEST: 'UPDATE_AVATAR_REQUEST',
  UPDATE_AVATAR_SUCCESS: 'UPDATE_AVATAR_SUCCESS',
  UPDATE_AVATAR_FAILURE: 'UPDATE_AVATAR_FAILURE',

  UPDATE_INFO_REQUEST: 'UPDATE_INFO_REQUEST',
  UPDATE_INFO_SUCCESS: 'UPDATE_INFO_SUCCESS',
  UPDATE_INFO_FAILURE: 'UPDATE_INFO_FAILURE',
};

export const BOOK = {
  LOAD_BOOK_LIST_REQUEST: 'LOAD_BOOK_LIST_REQUEST',
  LOAD_BOOK_LIST_SUCCESS: 'LOAD_BOOK_LIST_SUCCESS',
  LOAD_BOOK_LIST_FAILURE: 'LOAD_BOOK_LIST_FAILURE',

  LOAD_BOOK_LIST_BY_CATEGORY_REQUEST: 'LOAD_BOOK_LIST_BY_CATEGORY_REQUEST',
  LOAD_BOOK_LIST_BY_CATEGORY_SUCCESS: 'LOAD_BOOK_LIST_BY_CATEGORY_SUCCESS',
  LOAD_BOOK_LIST_BY_CATEGORY_FAILURE: 'LOAD_BOOK_LIST_BY_CATEGORY_FAILURE',

  LOAD_BOOK_REQUEST: 'LOAD_BOOK_REQUEST',
  LOAD_BOOK_SUCCESS: 'LOAD_BOOK_SUCCESS',
  LOAD_BOOK_FAILURE: 'LOAD_BOOK_FAILURE',

  LOAD_MY_BOOK_LIST_REQUEST: 'LOAD_MY_BOOK_LIST_REQUEST',
  LOAD_MY_BOOK_LIST_SUCCESS: 'LOAD_MY_BOOK_LIST_SUCCESS',
  LOAD_MY_BOOK_LIST_FAILURE: 'LOAD_MY_BOOK_LIST_FAILURE',

  CHANGE_BOOK_STATUS: 'CHANGE_BOOK_STATUS',
};

export const CATEGORY = {
  LOAD_CATEGORY_LIST_REQUEST: 'LOAD_CATEGORY_LIST_REQUEST',
  LOAD_CATEGORY_LIST_SUCCESS: 'LOAD_CATEGORY_LIST_SUCCESS',
  LOAD_CATEGORY_LIST_FAILURE: 'LOAD_CATEGORY_LIST_FAILURE',
};

export const LENDING = {
  BORROW_BOOK_REQUEST: 'BORROW_BOOK_REQUEST',
  BORROW_BOOK_SUCCESS: 'BORROW_BOOK_SUCCESS',
  BORROW_BOOK_FAILURE: 'BORROW_BOOK_FAILURE',

  CANCEL_BORROW_REQUEST: 'CANCEL_BORROW_REQUEST',
  CANCEL_BORROW_SUCCESS: 'CANCEL_BORROW_SUCCESS',
  CANCEL_BORROW_FAILURE: 'CANCEL_BORROW_FAILURE',

  ACCEPT_LENDING_REQUEST: 'ACCEPT_LENDING_REQUEST',
  ACCEPT_LENDING_SUCCESS: 'ACCEPT_LENDING_SUCCESS',
  ACCEPT_LENDING_FAILURE: 'ACCEPT_LENDING_FAILURE',

  REJECT_LENDING_REQUEST: 'REJECT_LENDING_REQUEST',
  REJECT_LENDING_SUCCESS: 'REJECT_LENDING_SUCCESS',
  REJECT_LENDING_FAILURE: 'REJECT_LENDING_FAILURE',

  RETURN_BOOK_REQUEST: 'RETURN_BOOK_REQUEST',
  RETURN_BOOK_SUCCESS: 'RETURN_BOOK_SUCCESS',
  RETURN_BOOK_FAILURE: 'RETURN_BOOK_FAILURE',

  LOAD_LATEST_LENDING_REQUEST: 'LOAD_LATEST_LENDING_REQUEST',
  LOAD_LATEST_LENDING_SUCCESS: 'LOAD_LATEST_LENDING_SUCCESS',
  LOAD_LATEST_LENDING_FAILURE: 'LOAD_LATEST_LENDING_FAILURE',

  LOAD_MY_REQUEST_LIST_BY_STATUS_REQUEST: 'LOAD_MY_REQUEST_LIST_BY_STATUS_REQUEST',
  LOAD_MY_REQUEST_LIST_BY_STATUS_SUCCESS: 'LOAD_MY_REQUEST_LIST_BY_STATUS_SUCCESS',
  LOAD_MY_REQUEST_LIST_BY_STATUS_FAILURE: 'LOAD_MY_REQUEST_LIST_BY_STATUS_FAILURE',

  LOAD_REQUEST_LIST_FOR_MY_BOOK_REQUEST: 'LOAD_REQUEST_LIST_FOR_MY_BOOK_REQUEST',
  LOAD_REQUEST_LIST_FOR_MY_BOOK_SUCCESS: 'LOAD_REQUEST_LIST_FOR_MY_BOOK_SUCCESS',
  LOAD_REQUEST_LIST_FOR_MY_BOOK_FAILURE: 'LOAD_REQUEST_LIST_FOR_MY_BOOK_FAILURE',
};

export const REVIEW = {
  LOAD_REVIEW_LIST_REQUEST: 'LOAD_REVIEW_LIST_REQUEST',
  LOAD_REVIEW_LIST_SUCCESS: 'LOAD_REVIEW_LIST_SUCCESS',
  LOAD_REVIEW_LIST_FAILURE: 'LOAD_REVIEW_LIST_FAILURE',

  SAVE_REVIEW_REQUEST: 'SAVE_REVIEW_REQUEST',
  SAVE_REVIEW_SUCCESS: 'SAVE_REVIEW_SUCCESS',
  SAVE_REVIEW_FAILURE: 'SAVE_REVIEW_FAILURE',

  UPDATE_REVIEW_REQUEST: 'UPDATE_REVIEW_REQUEST',
  UPDATE_REVIEW_SUCCESS: 'UPDATE_REVIEW_SUCCESS',
  UPDATE_REVIEW_FAILURE: 'UPDATE_REVIEW_FAILURE',

  DELETE_REVIEW_REQUEST: 'DELETE_REVIEW_REQUEST',
  DELETE_REVIEW_SUCCESS: 'DELETE_REVIEW_SUCCESS',
  DELETE_REVIEW_FAILURE: 'DELETE_REVIEW_FAILURE',

  LOAD_MY_REVIEW_LIST_REQUEST: 'LOAD_MY_REVIEW_LIST_REQUEST',
  LOAD_MY_REVIEW_LIST_SUCCESS: 'LOAD_MY_REVIEW_LIST_SUCCESS',
  LOAD_MY_REVIEW_LIST_FAILURE: 'LOAD_MY_REVIEW_LIST_FAILURE',
};

export const REGISTER = {
  UPLOAD_IMAGE_REQUEST: 'UPLOAD_IMAGE_REQUEST',
  UPLOAD_IMAGE_SUCCESS: 'UPLOAD_IMAGE_SUCCESS',
  UPLOAD_IMAGE_FAILURE: 'UPLOAD_IMAGE_FAILURE',

  REGISTER_BOOK_REQUEST: 'REGISTER_BOOK_REQUEST',
  REGISTER_BOOK_SUCCESS: 'REGISTER_BOOK_SUCCESS',
  REGISTER_BOOK_FAILURE: 'REGISTER_BOOK_FAILURE',

  CLEAR: 'CLEAR',
};
